### PR TITLE
Organization user affiliation error

### LINKED ISSUE #2463: Organization page is broken for "USER"s of orgs
Frontend break when viewing an organization's page with only "USER" level permissions. "USER"s are not allowed to view organization affiliations.

```
{
  "errors": [
    {
      "message": "Cannot query affiliations on organization without admin permission or higher.",
      "locations": [
        {
          "line": 33,
          "column": 5
        }
      ],
      "path": ["organization", "affiliations"],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by AdamPrins**
adds a isUserAdmin query to the org details page.
If the user is not an admin, the Users tab is not rendered

fixes #2463

### CODE REVIEW

File: frontend/src/OrganizationDetails.js [hunk 1]
```diff
@@ -46,6 +46,31 @@ export default function OrganizationDetails() {
...
+    },
+  })
+
+  let isAdmin = false
+  if (isAdminData?.isUserAdmin) {
+    isAdmin = isAdminData.isUserAdmin
+
+  }
+  console.log("isAdmin: " + isAdmin)
+
```
Comment (lcampbell2) [inline frontend/src/OrganizationDetails.js:73]: Just need to delete the console.log() and clean up the spacing and LGTM

**Review by lcampbell2 — CHANGES_REQUESTED** [review]

**Review by lcampbell2 — APPROVED** [review]
