### PR TITLE
Fe add search and ordering to dmarc summaries

### LINKED ISSUE #2128: Date changer on DMARC summary page doesn't work
Changing the date modifying does not cause a network request for the new date.

Fix:
Modify cache to make date keyfields

### PR DESCRIPTION
**Pull request by FestiveKyle**
As described. Also:
- Changes loading spinner design
- Removes "no sort" option for dmarc summary table (2 options for each column instead of 3)
- Adds useDebounce, helpful for reducing the number of wasteful fetches
- Closes #2128

### CODE REVIEW

**Review by lcampbell2 — APPROVED** [review]

File: frontend/src/helpers/toConstantCase.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import { upperCase } from 'lodash'
+
+export const toConstantCase = (str) => {
+  return upperCase(str).replace(/ /g, '_')
```
Comment (sleepycat) [inline frontend/src/helpers/toConstantCase.js:4]: Let's not create a dependency on Lodash for this. If we change this to `str.toUpperCase().replace(/ /g, '_')`, it'll give us the same behaviour without dragging in new a dependency.

**Review by sleepycat — CHANGES_REQUESTED** [review]
One minor change! The rest looks good!

File: frontend/src/helpers/toConstantCase.js (hunk 1 above)
Comment (FestiveKyle) [reply frontend/src/helpers/toConstantCase.js]: Done 👍 

```
export const toConstantCase = (str) => {
  return str.toUpperCase().replace(/ /g, '_')
}

```
